apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: djelinska/ecommerce-app-project:backend
          ports:
            - containerPort: 7000
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: mongo-url
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: frontend-url
            - name: KEYCLOAK_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: keycloak-server-url
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: keycloak-realm
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: keycloak-client-id
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mongo-password

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
