apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: djelinska/ecommerce-app-project:frontend
          ports:
            - containerPort: 3000
          env:
            - name: VITE_KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: vite-keykloak-url
            - name: VITE_KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: vite-keykloak-realm
            - name: VITE_KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: vite-keykloak-client-id
            - name: VITE_KEYCLOAK_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: vite-keykloak-redirect-uri
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: vite-api-base-url
          resources:
            requests:
              memory: '256Mi'
            limits:
              memory: '512Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
